variables:
  DOCKER_DRIVER: overlay2
  DOCKER_IMAGE_API: registry.gitlab.com/dnu-dreamteam/dolgov/api

services:
- docker:dind

stages:
- build-api-with-containers
- deploy

build-api-with-containers:
  image: docker:latest
  stage: build-api-with-containers
  before_script:
  - apk update && apk add git
  - cd ./api/
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  script:
  - export VERSION=$(date +%y.%m)
  - echo $VERSION
  - >
    docker run -t --rm
    -v /var/run/docker.sock:/var/run/docker.sock
    -v "$(pwd)":"$(pwd)"
    -w "$(pwd)"
    -u 0:0
    maven:3-jdk-8
    mvn clean package -Pdocker -DdockerImageTags=$VERSION
  - docker push $DOCKER_IMAGE_API:$VERSION -P
  after_script:
  - cd /
  artifacts:
    paths:
    - ./api/target/api-0.0.1-SNAPSHOT.jar
    when: always
#  only:
#  - master

deploy:
  stage: deploy
  before_script:
  - apt-get update -y && apt-get install sshpass
  script:
  - sshpass -p "${DEPLOYMENT_SERVER_PASS}" scp -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o PubkeyAuthentication=no ./infrastructure/docker-compose.yml ${DEPLOYMENT_SERVER_USER}@${DEPLOYMENT_SERVER_IP}:~/
  - sshpass -p "${DEPLOYMENT_SERVER_PASS}" scp -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o PubkeyAuthentication=no -r ./infrastructure/balancer ${DEPLOYMENT_SERVER_USER}@${DEPLOYMENT_SERVER_IP}:~/
  - sshpass -p $DEPLOYMENT_SERVER_PASS ssh -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o PubkeyAuthentication=no $DEPLOYMENT_SERVER_USER@$DEPLOYMENT_SERVER_IP "sudo docker-compose -f docker-compose.yml stop; sudo docker-compose -f docker-compose.yml rm web --force; sudo docker-compose -f docker-compose.yml build; sudo docker-compose -f docker-compose.yml pull; sudo docker-compose -f docker-compose.yml up -d;"
#  only:
#  - master
