// SIGN UP
export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST '
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS '
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR '

export const VERIFY_ACCOUNT_REQUEST = 'VERIFY_ACCOUNT_REQUEST'
export const VERIFY_ACCOUNT_SUCCESS = 'VERIFY_ACCOUNT_SUCCESS'
export const VERIFY_ACCOUNT_ERROR = 'VERIFY_ACCOUNT_ERROR'

// SIGN IN
export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST '
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS '
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR '

export const REFRESH_AUTH_FROM_STORE = 'REFRESH_AUTH_FROM_STORE'
