version: '3.3'
services:
  nginx:
    build: ./balancer
    restart: always
    links:
      - "api:api"
      - "ui:ui"
      - "docs-api:docs-api"
    ports:
    - "80:80"

  postgres:
    image: sameersbn/postgresql:9.6-2
    ports:
    - "5433:5432"
    command: '-N 500'
    environment:
    - DEBUG=false
    - PG_TRUST_LOCALNET=true
    - PG_PASSWORD=postgres
    - DB_NAME=api_db,docs_api_db

  ui:
    image:  registry.gitlab.com/dnu-dreamteam/dolgov/ui
    restart: always
    ports:
    - "80"

  docs-api:
    image: registry.gitlab.com/dnu-dreamteam/dolgov/docs-api
    restart: always
    environment:
    - JVM_MEMORY_OPTS=-Dspring.datasource.url=jdbc:postgresql://postgres:5432/docs_api_db -Dspring.datasource.username=postgres -Dspring.datasource.password=dreamteam -Dserver.port=8080 -Dauth.publicKey=/secret/fake-publickey.der
    links:
    - "postgres:postgres"
    ports:
    - "8080"
    volumes:
    - "./data/secret/:/secret/"

  api:
    image:  registry.gitlab.com/dnu-dreamteam/dolgov/api
    restart: always
    environment:
    - JVM_MEMORY_OPTS=-Dspring.datasource.url=jdbc:postgresql://postgres:5432/api_db -Dspring.datasource.username=postgres -Dspring.datasource.password=postgres -Dserver.port=8080 -Dauth.privateKey=/secret/fake-privatekey.der -Dauth.publicKey=/secret/fake-publickey.der
    links:
    - "postgres:postgres"
    volumes:
    - "./data/secret/:/secret/"
    ports:
    - "8080"


