
export const SIGN_UP = 'SIGN_UP'
export const VERIFY_ACCOUNT = 'VERIFY_ACCOUNT'
export const SIGN_IN = 'SIGN_IN'
export const REFRESH_AUTH_FROM_STORE = 'REFRESH_AUTH_FROM_STORE'
export const LOGOUT = 'LOGOUT'
export const ACTIVATE_INVITATION_LINK = 'ACTIVATE_INVITATION_LINK'
