export const SIGN_IN = 'SIGN_IN'
export const LOGOUT = 'LOGOUT'
export const SIGN_UP = 'SIGN_UP'
export const VERIFY_ACCOUNT = 'VERIFY_ACCOUNT'

export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR'
export const REFRESH_AUTH_FROM_STORE = 'REFRESH_AUTH_FROM_STORE'
export const ACTIVATE_INVITATION_LINK = 'ACTIVATE_INVITATION_LINK'
