export const GET_BOARDS_PREVIEWS = 'GET_BOARDS_PREVIEWS'
export const GET_BOARD_BY_ID = 'GET_BOARD_BY_ID'
export const SET_CURRENT_BOARD = 'SET_CURRENT_BOARD'
export const CREATE_BOARD = 'CREATE_BOARD'
